### ISSUE TITLE
Problem using TruePath with Microsoft Surface Pro Laptop

### ISSUE THREAD

**Issue by wd66dev** [gsumit1/TruePath#1]
TruePath v3,0 added to firefox v61.0.1 (64bit):

when I click on the relative xpath no pop-up window is displayed allowing me to copy the xpath.

It is workign on a Lenovo Thinkpad with the same versions of FF loaded.

Is there a setting or another plugin required for Microsoft laptop.?

**Comment by gsumit1** [comment]
There is no settings or extra plugin required to use this extension.
I also retried  for FF v61.0.1+Windows 10, it is working fine. I am limited with Microsoft Surface Pro laptop to debug this issue. 

You can try chrome edition. here is the link:
https://chrome.google.com/webstore/detail/truepath/mgjhkhhbkkldiihlajcnlfchfcmhipmn?hl=en

**Comment by wd66dev** [comment]
Thanks for your response I will try the link ;0)

On 25 Jul 2018, at 06:33, Sumit Ghosh <notifications@github.com<mailto:notifications@github.com>> wrote:


There is no settings or extra plugin required to use this extension.
I also retried for FF v61.0.1+Windows 10, it is working fine. I am limited with Microsoft Surface Pro laptop to debug this issue.

You can try chrome edition. here is the link:
https://chrome.google.com/webstore/detail/truepath/mgjhkhhbkkldiihlajcnlfchfcmhipmn?hl=en
